/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vivisystem_com_test_jni_TestNative */

#ifndef _Included_vivisystem_com_test_jni_TestNative
#define _Included_vivisystem_com_test_jni_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vivisystem_com_test_jni_TestNative
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vivisystem_com_test_1jni_TestNative_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
